1. Create a class Employee and then do the following
• Create a data member to count the number of Employees
• Create a constructor to initialize name, family, salary, department
• Create a function to average salary
• Create a Fulltime Employee class and it should inherit the properties of Employee class
• Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [2]:
class Employee:
    employee_count = 0  # Data member to count the number of Employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, total_salary):
        return total_salary / Employee.employee_count

class FulltimeEmployee(Employee):
    # Inheriting properties from the Employee class
    pass

# Creating instances of Employee class
employee1 = Employee("tarak", "nandamuri", 500000, "HR")
employee2 = Employee("charan", "konidela", 80000, "IT")

# Creating instances of FulltimeEmployee class
fulltime_employee1 = FulltimeEmployee("chay", "akkeneni", 50000, "Finance")
fulltime_employee2 = FulltimeEmployee("akhil", "nalabolu", 90000, "Marketing")

# Calling member functions
total_salary_employees = employee1.salary + employee2.salary
average_salary_employees = employee1.average_salary(total_salary_employees)

total_salary_fulltime_employees = fulltime_employee1.salary + fulltime_employee2.salary
average_salary_fulltime_employees = fulltime_employee1.average_salary(total_salary_fulltime_employees)

# Displaying results
print("Average Salary for Employees:", average_salary_employees)
print("Average Salary for Fulltime Employees:", average_salary_fulltime_employees)


Average Salary for Employees: 145000.0
Average Salary for Fulltime Employees: 35000.0


2. Numpy
Using NumPy create random vector of size 20 having only float in the range 1-20.
Then reshape the array to 4 by 5
Then replace the max in each row by 0 (axis=1)

In [3]:
# Import the NumPy library and alias it as 'np' for brevity and convention.
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

print("Original Random Vector:\n", random_vector)

Original Random Vector:
 [15.76197542  9.08749031 14.31240116  7.03564316  7.8077146   4.32096153
 13.9184916   3.3040662  19.44058611  6.26122328 12.91380131  8.88618823
  4.10382004  8.48407706 15.96550348 11.99378757 18.41118827  3.40834627
 19.4365328  14.90734053]


In [4]:
# Reshape the array to 4 by 5 (4 rows and 5 columns)
reshaped_array = random_vector.reshape(4, 5)

print(reshaped_array)

[[15.76197542  9.08749031 14.31240116  7.03564316  7.8077146 ]
 [ 4.32096153 13.9184916   3.3040662  19.44058611  6.26122328]
 [12.91380131  8.88618823  4.10382004  8.48407706 15.96550348]
 [11.99378757 18.41118827  3.40834627 19.4365328  14.90734053]]


In [5]:
# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[ 0.          9.08749031 14.31240116  7.03564316  7.8077146 ]
 [ 4.32096153 13.9184916   3.3040662   0.          6.26122328]
 [12.91380131  8.88618823  4.10382004  8.48407706  0.        ]
 [11.99378757 18.41118827  3.40834627  0.         14.90734053]]


video link:https://drive.google.com/file/d/1jzpQ7cvuWkIhYFfVKp7dPV7MHsZ-irD0/view?usp=drive_link